[metadata]
name = "test"
size = 16
last_change = 1660260950

[members.0]
member_name = "field_0"
offset = 0
type = ""
size = 4

[members.4]
member_name = "field_4"
offset = 4
type = ""
size = 4

[members.8]
member_name = "field_8"
offset = 8
type = ""
size = 4

[members.c]
member_name = "field_C"
offset = 12
type = ""
size = 4
